[FRO-5] Button Component
webdevmajstry/001-zero-waste pull request #1
Opened 2022-11-24 21:36 UTC by Rmichal503

<img width="313" alt="Zrzut ekranu 2022-11-24 o 22 06 02" src="https://user-images.githubusercontent.com/93224847/203865254-fc93ea55-a9b5-462a-9028-0eae3967dbe6.png">

I created button component based on existing code, extend button type by two additional props (variant and size).
I also added 4 custom class to tailwind (default, btn, btn-small and btn-large).

2022-11-25 20:36 UTC, patryk-bernasiewicz requested changes
Additional thing you could look into is expanding the tests for the `Button` component. Unit/component test are the kind where you can actually look at the implementation details, so you could also test for the `variant` and `size` props and see whether the DOM element receives valid classes after the props have been passed to the component.

2022-11-25 20:36 UTC, patryk-bernasiewicz commented on src/components/Button/Button.tsx
> +export type ButtonProps = ButtonHTMLAttributes<HTMLButtonElement> & {variant?:string,size?:string};
Types use semicolon for separation, eg.
```typescript
type Type = {
    variant?: string;
    size?: string;
}
```

2022-11-25 20:36 UTC, patryk-bernasiewicz commented on src/components/Button/Button.tsx
> +    }
Don't use `switch` instruction to handle such problems. It's much better to use a dictionary approach, example:

```typescript
const variantClasses = {
    small: 'btn-small',
    large: 'btn-large',
    default: 'btn',
};
```
and then:
```typescript
btnClass = variantClasses[variant];

```

2022-11-25 20:36 UTC, patryk-bernasiewicz commented on src/styles/globals.css
> +    }
I don't think that creating separate CSS classes for button variants is necessary. We don't plan to re-use these anywhere, as the `Button` component is supposed to be solely responsible for providing button-related functionality.

It would be much better to keep this list of classes as an object literal inside the `Button.tsx` file and then pick them as properties (see previous comment about dictionary approach)

2022-11-25 20:36 UTC, patryk-bernasiewicz commented on src/styles/globals.css
> +        @apply bg-primary-500 text-light-100 hover:bg-primary-400
I can see you handled the `:hover` state here, it's very nice :) The only thing that's missing is also handling the `:focus`

2022-11-25 20:36 UTC, patryk-bernasiewicz commented on src/components/Button/Button.test.tsx
> +    render(<Button onClick={onClick} variant={''} size={''}>Click me</Button>);
The `variant` and `size` props should be optional for the component, so they could be safely removed from the tests

2022-11-26 19:30 UTC, Ebmili commented
> <img alt="Zrzut ekranu 2022-11-24 o 22 06 02" width="313" src="https://user-images.githubusercontent.com/93224847/203865254-fc93ea55-a9b5-462a-9028-0eae3967dbe6.png">
> 
> I created button component based on existing code, extend button type by two additional props (variant and size). I also added 4 custom class to tailwind (default, btn, btn-small and btn-large).

I believe that storybook file needs to be updated too. I think it should display three variants of the button, right now it displays the old version of the button.

2022-11-27 14:28 UTC, Rmichal503 commented
@Ebmili, check now, i added extra buttons in storybook and also installed addon for storybook to use tailwind in it

2022-11-28 08:59 UTC, patryk-bernasiewicz requested changes

2022-11-28 08:59 UTC, patryk-bernasiewicz commented on src/components/Button/Button.tsx
> +    }
This does not need to be initialized within the component, as it will be re-initialized on every render. Please move the variable above the component declaration.

2022-11-28 08:59 UTC, patryk-bernasiewicz commented on src/components/Button/Button.tsx
> +    const variantClasses:any = {
Please try to not use `any`, in this case it could look like that:

```typescript
type ButtonVariants = 'small' | 'default' | 'large';

const variantClasses: Record<ButtonVariants, string> = { ... };
```

Also, the single-word object literal properties don't need quotes

2022-11-28 08:59 UTC, patryk-bernasiewicz commented on src/components/Button/Button.tsx
> +    const variantClasses:any = {
Please try to not use `any`, in this case it could look like that:

```typescript
type ButtonVariants = 'small' | 'default' | 'large';

const variantClasses: Record<ButtonVariants, string> = { ... };
```

Also, the single-word object literal properties don't need quotes.

I'm going to update the Eslint config to handle these cases later today

2022-11-28 08:59 UTC, patryk-bernasiewicz commented on src/components/Button/Button.stories.tsx
> +  children: 'Small button',
Please use `argTypes` to define options for `variant`, instead of separate stories. https://storybook.js.org/docs/react/api/argtypes

2022-11-28 17:32 UTC, Ebmili commented
> @Ebmili, check now, i added extra buttons in storybook and also installed addon for storybook to use tailwind in it

Hi, I still see only one version of the button and also can't see any styles has been applied in storybook.

2022-11-30 12:29 UTC, patryk-bernasiewicz commented
@Ebmili they've been addes as `argTypes`

```
  argTypes:{
    ...
    variant:{
      options:['small','default','large'],
      control:{type:'radio'},
      defaultValue:'default',
      type:{
        name:'string'
      }
    }
  }
```

2022-11-30 12:31 UTC, patryk-bernasiewicz approved these changes
LGTM 🚀

2022-12-05 14:21 UTC, KatSobieska commented
Is defaultValue in argTypes defined by some rules? If not, I think we should stick to one language. (Log in)
Besides, everything looks great :)

2022-12-05 18:39 UTC, Rmichal503 commented
@Ebmili I’ve added the text that was in Jira ticket and it’s only to show how button looks like with text. But it’s no problem to change it 😁

2022-12-06 15:46 UTC, Ebmili approved these changes
Looks good to go :)

2022-12-06 19:48 UTC, patryk-bernasiewicz commented
Looks like it's ready for merge ;) @Rmichal503

2022-12-06 21:27 UTC, merged