[FR0-9] Rating Component
webdevmajstry/001-zero-waste pull request #6
Opened 2022-12-01 12:04 UTC by Rmichal503

Created Rating Component with two variants: :heart: and :star:. 
Each variant have three types: default, number and hidden (on screenshot from top: hidden, default, number).
Icons are generated based on "rate" prop
<img width="167" alt="Zrzut ekranu 2022-12-1 o 12 43 27" src="https://user-images.githubusercontent.com/93224847/205046584-c5d5d249-0929-450c-a723-b39250954cea.png">
PR is without test file because Jest doesn't like svgr (for now 😛)

2022-12-02 22:39 UTC, patryk-bernasiewicz requested changes
The PR got messed up by my changes in the `main` branch, but that's okay - the next ones should be working properly

2022-12-02 22:39 UTC, patryk-bernasiewicz commented on src/components/Rating/Rating.stories.tsx
> +const Template: Story = (args) => <Rating rate={0} {...args}/>
`rate` prop comes from `args` so it doesn't have to explicitly set here

2022-12-02 22:39 UTC, patryk-bernasiewicz commented on src/components/Rating/Rating.test.tsx
> +    // })
This test can be removed completely as we're not going to use `img`s

2022-12-02 22:39 UTC, patryk-bernasiewicz commented on src/components/Rating/Rating.tsx
> +    {rate>0?<div key={`${type}${variant}${rate}`} className="flex items-center">
You can simplify and flatten this condition by moving it above the default render, eg.

```typescript
if (rate <= 0) {
    return null;
}

return (
    <div>...</div>
);

```

2022-12-02 22:39 UTC, patryk-bernasiewicz commented on src/components/Rating/Rating.tsx
> +export type RatingProps = { variant?: string; type?: string; rate: number };
`variant` should explicitly have type of either 'stars' or 'hearts'. Same goes for `type` - it should list only the allowed strings.

2022-12-02 22:39 UTC, patryk-bernasiewicz commented on src/components/Rating/Rating.tsx
> +  const { variant , type = 'default', rate } = props;
You can perform destructurization directly in the parentheses, but that's a matter of preference :)

2022-12-02 22:39 UTC, patryk-bernasiewicz commented on src/components/Rating/Rating.tsx
> +                  : 'mx-px opacity-50'
You could store such condition in a variable, eg.

```typescript
const isActive = index < rate;
const isHidden = type === 'hidden';
```
and then use [clsx](https://www.npmjs.com/package/clsx) package to join classes with conditions
```typescript
import clsx from 'clsx';

const iconClasses = clsx(
    'mx-px',
    isHidden && 'hidden',
    !isActive && !isHidden && 'opacity-50'
);
```

The way it works is it joins the strings which have a truthy value on the left side of their condition. See more in the package's README: [https://github.com/lukeed/clsx#readme](github: clsx)

2022-12-02 22:39 UTC, patryk-bernasiewicz commented on src/components/Rating/Rating.tsx
> +      {type === 'number' ? <span>{rate}</span> : null}
You can use simplified conditional rendering like 

```tsx
{type === 'number' && <span>{rate}</span>}
```

2022-12-03 18:05 UTC, Rmichal503 commented on src/components/Rating/Rating.stories.tsx
> +const Template: Story = (args) => <Rating rate={0} {...args}/>
without `rate` prop I've got error. But I checked now without this prop and it's working perfect, with error in vsc but works :D

2022-12-05 17:06 UTC, patryk-bernasiewicz approved these changes
Looks great! 🚀

2022-12-07 10:02 UTC, bialek-k approved these changes

2022-12-07 10:04 UTC, merged