Created base for Input component.
webdevmajstry/001-zero-waste pull request #8
Opened 2022-12-05 08:25 UTC by Ebmili

Creating draft and base for the Input Component.

2022-12-06 19:47 UTC, patryk-bernasiewicz commented on src/components/Input/Input.stories.tsx
> +}
Also the `Fragment` doesn't seem to be necessary here

2022-12-15 15:56 UTC, Rmichal503 requested changes

2022-12-15 15:56 UTC, Rmichal503 commented on src/components/Input/Input.tsx
> +}
Try this:
```
import React, {InputHTMLAttributes } from 'react';

type CustomInputProps = InputHTMLAttributes<HTMLInputElement> & {
    label:string;
    helperText: string;
    errorText?: string;
```

2022-12-15 15:56 UTC, Rmichal503 commented on src/components/Input/Input.tsx
> +    }
I don't understand what this function introduces to the component. If it's a validation, then (if I'm not mistaken @patryk-bernasiewicz ?) it will be injected later by an external library

2022-12-15 15:56 UTC, Rmichal503 commented on src/components/Input/Input.tsx
> +    }
With the type that I proposed in the first comment, it will not be needed

2022-12-15 15:56 UTC, Rmichal503 commented on src/components/Input/Input.tsx
> +    ;
For me now with props 
`label: "Label for input"
value: "value"
placeholder:"placeholder"
`
 it looks like this:

<img width="227" alt="Zrzut ekranu 2022-12-15 o 16 28 46" src="https://user-images.githubusercontent.com/93224847/207906738-18383f81-4cb5-4277-8957-0b27858d6c1d.png">

2023-06-01 10:04 UTC, closed without merging